### ISSUE TITLE
Roadmap for lib Isometric Grid 0.1

### ISSUE THREAD

**Issue by whybtech** [epsilings/labs#1]
Setup grid with D3 and associated tests

TODO : 
- [x] Add D3.js to angular project
- [x] Create a simple grid with cube using isometric transformations
- [ ] Manage navigation on the grid using key board 
- [ ] Build basic shapes
- [ ] Add layers for multiple grids
- [ ] Manage animation for changing orientation of axes
- [ ] Add a toolbar with buttons to manage the grid actions (navigation and changing orientation)
